name:                first-haskell-stack
version:             0.1.0.0
github:              "GaborSzabo7/first-haskell-stack"
license:             BSD3
author:              "Gabor Szabo"
maintainer:          "gaszabo7@gmail.com"
copyright:           "Copyright (c) 2018 Gabor Szabo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            First

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/GaborSzabo7/first-haskell-stack#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  first-haskell-stack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - first-haskell-stack

tests:
  first-haskell-stack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - first-haskell-stack
